[package]
name = "flag"
version = "0.1.0"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]

[dependencies]
glfw = "0.21.0"
gl = "0.10.0"
libtga = { git = "https://github.com/stallmanifold/libtga" }
